services:
  - type: web
    name: dayflow-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_JWT_SECRET
        generateValue: true

      - key: APP_UPLOAD_DIR
        value: ./uploads/documents

      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlite:dayflow.db
